engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  tslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - typescript
exclude_paths:
- "demo/"
- "dist/"
- "docs/"
- "node_modules/"
- "tools/"