language: node_js
sudo: false
dist: dist
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
script:
  - npm run build
before_script:
  - npm prune
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/